---
title: "Build a MultiAssayExperiment from CCLE multi-omics data"
author: "Javier Perales-Patón - javier.perales@bioquant.uni-heidelberg.de - ORCID: 0000-0003-0780-6683" 
output: github_document
---

## Environment

### File structure
```{r env}
options(stringsAsFactors = FALSE)
# Seed number
set.seed(1234)

# input dir
INDIR <- "./raw/"

# Output directory
OUTDIR <- "./data/"
if(!dir.exists(OUTDIR)) dir.create(OUTDIR);

# Figures
FIGDIR <- "./fig/"
knitr::opts_chunk$set(fig.path=FIGDIR)
knitr::opts_chunk$set(dev=c('png'))

# Data
DATADIR <- OUTDIR
if(!dir.exists(DATADIR)) dir.create(DATADIR);

# If already exists, clean dirs?
clean_dirs <- TRUE
if(clean_dirs) {
	unlink(list.files(DATADIR, full.names=TRUE, recursive = TRUE))
	unlink(list.files(FIGDIR, full.names=TRUE, recursive = TRUE))
}
```

### Libraries
```{r libs}
# library(Biobase)
suppressPackageStartupMessages(library(SummarizedExperiment))
suppressPackageStartupMessages(library(RaggedExperiment))
suppressPackageStartupMessages(library(MultiAssayExperiment))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(UpSetR))
suppressPackageStartupMessages(library(ComplexHeatmap))
```

## Read data 
The following raw data was obtained directly from CCLE's FTP repository after accepting its LICENSE,
and the DepMap's FigShare, or custom laboratories websites. Use `make` to get all raw data. 

```{r find_files}
## Omics
fls <- list.files(INDIR, pattern="\\.(csv|gct)(\\.gz)?", full.names = TRUE)
fls <- grep("info", fls, invert=TRUE, value=TRUE)
names(fls) <- sapply(gsub("^(CCLE|Achilles)_", "", basename(fls)), function(z) strsplit(z, split="_")[[1]][1])
names(fls) <- gsub("\\.(csv|gct)(\\.gz)?","", names(fls))

## Info
ifls <- list.files(INDIR, pattern=".*info.*\\.(csv|gct)(\\.gz)?", full.names = TRUE)
names(ifls) <- sapply(gsub("^CCLE_", "", basename(ifls)), function(z) strsplit(z, split="_")[[1]][1])

# Show which omics and files
print(fls)
```

```{r read_files}
read_raw <- function(fl, omic) {
	if(omic == "metabolomics") {
		tab <- read.table(fl, sep=",", header=TRUE, 
				  stringsAsFactors = FALSE, 
				  check.names = FALSE)
	} else if (omic == "mutations") {
		tab <- read.table(fl, sep="\t", header=TRUE,
				  stringsAsFactors = FALSE,
				  check.names = FALSE)

	} else if (omic == "GCN" || omic == "GeneEssentiality") {
		tab <- read.table(fl, sep=",", header=TRUE,
				  stringsAsFactors = FALSE,
				  check.names = FALSE)
		colnames(tab)[1] <- "DepMapID"
	} else if (omic == "RNAseq") {
		tab <- read.table(fl, sep="\t", header=TRUE,
				  stringsAsFactors = FALSE,
				  check.names = FALSE,
				  skip = 2)
	} else if (omic == "RPPA") {
		tab <- read.table(fl, sep=",", header=TRUE, 
				  stringsAsFactors = FALSE, 
				  check.names = FALSE)
	} else if (omic == "protein") {
		tab <- read.table(fl, sep=",", header=TRUE, 
				  stringsAsFactors = FALSE, 
				  check.names = FALSE)
	} else {
		stop(paste0("OMIC not supported:", omic))
	}
	return(tab)

}
```

```{r metadata}
meta <- read.table(ifls["sample"], sep=",", header=TRUE,quote = '"',
		   stringsAsFactors = FALSE, check.names=FALSE)
stopifnot(!any(duplicated(meta$CCLE_Name)))
rownames(meta) <- meta$CCLE_Name
# meta_int <- c("DepMap_ID", "COSMICID", "sex", "culture_type", "culture_medium", 
# 	  "sample_collection_site", "primary_or_metastasis", "primary_disease", 
# 	  "Subtype", "age", "Sanger_Model_ID")
DepMap2CCLE <- setNames(meta$CCLE_Name, meta$DepMap_ID)
```

## Process data

```{r process_raw}
for(omic in names(fls)) {
	if(omic == "metabolomics") {
		tab <- read_raw(fls[omic], omic)
		rownames(tab) <- tab$CCLE_ID
		tab <- t(tab[, -c(1:2) ])
		res <- as.matrix(tab)
	} else if (omic == "mutations") {
		tab <- read_raw(fls[omic], omic)
		tab$Tumor_Sample_Barcode <- DepMap2CCLE[tab$Tumor_Sample_Barcode]
		# Inspired by: https://github.com/waldronlab/MultiAssayExperiment-CCLE/blob/master/R/ccleMAEO.R#L106-L113
		res <- makeGRangesListFromDataFrame(tab,
                                      names.field = "Hugo_Symbol",
                                      split.field = "Tumor_Sample_Barcode",
                                      start.field = "Start_position",
                                      end.field = "End_position",
                                      keep.extra.columns = TRUE)

		res <- RaggedExperiment(res)

	} else if (omic == "GCN" || omic == "GeneEssentiality") {
		tab <- read_raw(fls[omic], omic)
		# From DepMap to CCLE
		tab$DepMapID <- DepMap2CCLE[tab$DepMapID]
		# Actually, two cell line are duplicated, so the second one is dropped
		tab <- tab[!duplicated(tab$DepMapID),]
		# One cell line is not mapping to CCLE
		tab <- tab[!is.na(tab$DepMapID),]
		# Set up row and col names
		rownames(tab) <- tab$DepMapID
		tab <- tab[,-1]
		colnames(tab) <- sapply(colnames(tab), function(z) strsplit(z, split=" ")[[1]][1])
		# Traspose the matrix for a feature x ccl
		res <- t(tab)

	} else if (omic == "RNAseq") {
		tab <- read_raw(fls[omic], omic)
		# We focus on gene symbol. Remove first column (ensembl_gene_id). Then
		# aggregate counts by summing them by gene symbol
		tab <- tab[, which(colnames(tab)!="Name")]
		tab <- aggregate(.~ Description, data=tab, sum)
		# Rename rows, remove extra column, transform into matrix
		rownames(tab) <- tab$Description
		tab <- tab[, which(colnames(tab)!="Description")]
		res <- as.matrix(tab)

	} else if (omic == "RPPA") {
		tab <- read_raw(fls[omic], omic)
		rownames(tab) <- tab[,1]
		tab <- t(tab[, -c(1) ])
		# Here read rowdat from info file
		rowDat <- read.table(ifls[omic], sep=",", header=TRUE,
				   stringsAsFactors = FALSE,
				   check.names = FALSE)
		rownames(rowDat) <- rowDat$Antibody_Name


		res <- SummarizedExperiment(assay=setNames(list(tab), omic),
# 					   colData = colDat,
					   rowData = rowDat)
	} else if (omic == "protein") {
		tab <- read_raw(fls[omic], omic)
		# Generate rowData
		rowDat <- tab[, 1:48]

		# Reformat mat
		tab <- tab[-c(1:48)]

		# Generate colData
		colDat <- sapply(colnames(tab),function(z) {
					 xx <- strsplit(z,split="_")[[1]]
					batch <- tail(xx,1)
					cellID <- paste(setdiff(xx, batch),collapse="_")
					return(c(cellID, batch))
				  })
		colDat <- as.data.frame(t(colDat))
		colnames(colDat) <- c("cellID","batch")
		# Init Nreplicates of instances
		colDat$Nreplicates <- 1

		# Handle replicates by average them
		if(any(duplicated(colDat$cellID))) {
			DupCellID <- colDat$cellID[duplicated(colDat$cellID)]
			cat(paste0("CL w/ >1 replicate: ", 
				   paste(DupCellID,collapse=","), 
				   "\n"),file=stdout())
			for(CL in DupCellID) {
				# Collect all index for cellID,
				# retrieve 1st to summarize as average
				# remove the rest
				CL.idx <- which(colDat$cellID==CL)
				CL.idx_1st <- CL.idx[1]
				CL.idx_rm <- CL.idx[-1]

				# Average signal
				tab[, CL.idx_1st] <- apply(tab[, CL.idx],1, function(z) mean(z, na.rm=TRUE))
				# Concatenate batches
				colDat[CL.idx_1st, "batch"] <- paste(colDat[CL.idx, "batch"], collapse=",")
				# Count N replicates
				colDat[CL.idx_1st, "Nreplicates"] <- sum(colDat[CL.idx, "Nreplicates"])

				# Remove replicates
				tab <- tab[, -CL.idx_rm]
				colDat <- colDat[-CL.idx_rm, ]

			}
		}
		rownames(colDat) <- colDat$cellID
		colnames(tab) <- colDat[colnames(tab), "cellID"]

		res <- SummarizedExperiment(assay=setNames(list(tab), omic),
					   colData = colDat,
					   rowData = rowDat)
	} else {
		stop("OMIC not supported")
	}

	assign(omic, res)
}
```

## MultiAssayExperiment : create and save it

```{r omics}
omics <- names(fls)
# Experiment List ----
dataList <- sapply(omics, get)
# Prepare the MultiAssayExperiment
MAE <- MultiAssayExperiment(experiments=dataList,
			    colData=meta)
```

```{r save}
print(MAE)
saveRDS(MAE, paste0(DATADIR,"/MAE.rds"))
# Save features per each omic
for(omic in names(assays(MAE))) {
	cat(rownames(assay(MAE, "metabolomics")),sep="\n",
	    file=paste0(DATADIR,"/features_",omic,".txt"))
}
```

```{r map}
sMap <- sampleMap(MAE)
write.table(as.data.frame(sMap), file=paste0(DATADIR,"/sample_map.csv"),
	    sep=",", row.names=FALSE, col.names=TRUE, quote=TRUE)
```

## Visualization
```{r hp, fig.width=14, fig.height=7, dpi=300}
set.seed(1213)
MAT <- reshape2::dcast(as.data.frame(sMap), primary ~ assay)
MAT <- MAT[,-1]
rownames(MAT) <- apply(MAT, 1, function(z) unique(na.omit(z)))
MAT[!is.na(MAT)] <- "Available"
MAT[is.na(MAT)] <- "NOT available"
MAT <- t(MAT)

df <- colData(MAE)[,c("primary_disease", "primary_or_metastasis",
		      "age", "culture_medium")]
hc <- HeatmapAnnotation(df=df, 
			annotation_legend_param = list(ncol=6),
			show_legend = c(TRUE, TRUE, TRUE, FALSE))
ha <- rowAnnotation("Sample_size"=anno_barplot(rowSums(MAT=="Available")),
		    annotation_width=unit(5, "cm"))
hp <- Heatmap(MAT,name="Data",
	      row_names_gp = gpar(fontsize=18),
		heatmap_legend_param = list(title_gp=gpar(fontsize=16),
					labels_gp=gpar(fontsize=16)),
	      show_row_names=TRUE, show_column_names=FALSE, 
	      row_names_side="left", top_annotation = hc) + ha
draw(hp, heatmap_legend_side="left", annotation_legend_side="bottom")
```

```{r upset, fig.width=10, fig.height=6, dpi=300}
listInput <- split(sMap$primary, sMap$assay)
upset(fromList(listInput), order.by = "freq", text.scale=2)
```
## Session info

```{r}
sessionInfo()

{                                                                                                                                                                                                           
sink(file=paste0(OUTDIR,"/sessionInfo.txt"))
print(sessionInfo())
sink()
}
```

